version: '3'
services:
  app:
    build: .
    container_name: nestjs-app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
