import "./globals.css";
import Navbar from "@/ui/Navbar";
import Footer from "@/ui/Footer";
import SessionWrapper from "@/ui/SessionWrapper";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <SessionWrapper>
        <body className={inter.className}>
          <Navbar />
          {children}
          <Footer />
          </body>
      </SessionWrapper>
    </html>
  );
}

